"""
Provenance Guard Flask API

A content attribution system that classifies text as human-written, AI-generated,
or uncertain. The system uses multiple detection signals and returns a confidence
score with a plain-English transparency label.

Milestone 3: Flask skeleton with POST /api/content/submit endpoint and Signal 1
integration (perplexity analysis).
"""

import uuid
import logging
from datetime import datetime
from typing import Dict, Any, Tuple

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from signal_1_perplexity import calculate_perplexity
from signal_2_linguistic_features import calculate_linguistic_score
from scoring_logic import classify_content
from src.audit_log import log_submission, get_log, get_submission_by_id
from label_generation import generate_appeal_endpoint, generate_label

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Initialize Flask app
app = Flask(__name__)

# Initialize rate limiter (100 requests per hour per IP)
limiter = Limiter(
    app=app,
    key_func=get_remote_address,
    default_limits=["100 per hour"],
    storage_uri="memory://",
)

# Register appeals endpoint
app = generate_appeal_endpoint(app)


# ============================================================================
# Input Validation
# ============================================================================

def validate_submission_input(data: Dict[str, Any]) -> Tuple[bool, str]:
    """
    Validate the submission request payload.

    Args:
        data: The JSON payload from the request.

    Returns:
        A tuple (is_valid, error_message). If is_valid is True, error_message is empty.
    """
    if not isinstance(data, dict):
        return False, "Request body must be a JSON object."

    # Check required fields
    if "text" not in data:
        return False, "Missing required field: 'text'."

    if "creator_id" not in data:
        return False, "Missing required field: 'creator_id'."

    text = data.get("text")
    creator_id = data.get("creator_id")

    # Validate text
    if not isinstance(text, str):
        return False, "Field 'text' must be a string."

    text = text.strip()
    if len(text) == 0:
        return False, "Field 'text' cannot be empty."

    if len(text) < 5:
        return False, "Field 'text' must be at least 5 characters long."

    if len(text) > 5000:
        return False, "Field 'text' exceeds maximum length of 5000 characters."

    # Validate creator_id
    if not isinstance(creator_id, str):
        return False, "Field 'creator_id' must be a string."

    if len(creator_id.strip()) == 0:
        return False, "Field 'creator_id' cannot be empty."

    return True, ""


# ============================================================================
# Transparency Label Generation
# ============================================================================

def generate_transparency_label(classification: str, confidence_score: float, signals: Dict[str, float]) -> str:
    """
    Generate a plain-English transparency label explaining the classification.

    Args:
        classification: One of "human", "ai", or "uncertain".
        confidence_score: The confidence score (0-1).
        signals: Dictionary with signal scores (e.g., {"perplexity": 0.75}).

    Returns:
        A human-readable label explaining the classification.
    """
    if classification == "human":
        return (
            "✓ Likely written by a human\n\n"
            "We're highly confident this content was written by a person.\n\n"
            "How we detected this:\n"
            "The writing shows natural variation in sentence structure and vocabulary "
            "choices that are typical of human authorship. The text uses diverse "
            "sentence lengths and includes natural discourse patterns."
        )
    elif classification == "ai":
        return (
            "⚠ Likely generated by AI\n\n"
            "We're highly confident this content was generated by an AI system, "
            "not written by a human.\n\n"
            "How we detected this:\n"
            "The text shows patterns of predictability and structural consistency "
            "that are typical of AI-generated content. Sentences have uniform length "
            "and structure, with formal discourse markers appearing systematically."
        )
    else:  # uncertain
        return (
            "? We're unsure about the authorship\n\n"
            "Our analysis suggests this content has characteristics of both human "
            "and AI writing.\n\n"
            "This might mean:\n"
            "• The content is a blend of human and AI (e.g., AI draft revised by a human)\n"
            "• The writing style is unusual for our detection system\n"
            "• The author writes in a very formal or mechanical way\n"
            "• The text is too short for reliable analysis\n\n"
            "If you're the creator and this is your original work, you can appeal "
            "this classification."
        )


# Note: classify_content is imported from scoring_logic.py
# It combines both Signal 1 (perplexity) and Signal 2 (linguistic features)


# ============================================================================
# API Endpoints
# ============================================================================

@app.route("/api/content/submit", methods=["POST"])
@limiter.limit("100 per hour")
def submit_content():
    """
    Submit text for classification.

    POST /api/content/submit
    {
        "text": "The text to classify...",
        "creator_id": "user_123"
    }

    Returns:
    {
        "submission_id": "uuid",
        "classification": "human|ai|uncertain",
        "confidence_score": 0.85,
        "signals": {
            "perplexity": 0.75
        },
        "transparency_label": "...",
        "timestamp": "2026-06-30T12:34:56Z"
    }
    """
    try:
        # Parse JSON
        data = request.get_json()
        if data is None:
            return jsonify({"error": "Request body must be valid JSON."}), 400

        # Validate input
        is_valid, error_msg = validate_submission_input(data)
        if not is_valid:
            logger.warning(f"Invalid submission input: {error_msg}")
            return jsonify({"error": error_msg}), 400

        text = data.get("text").strip()
        creator_id = data.get("creator_id").strip()

        # Calculate Signal 1: Perplexity
        try:
            perplexity_score = calculate_perplexity(text)
        except Exception as e:
            logger.error(f"Error calculating perplexity: {str(e)}")
            perplexity_score = 0.5  # Default to neutral on error

        # Calculate Signal 2: Linguistic Features
        try:
            linguistic_score = calculate_linguistic_score(text)
        except Exception as e:
            logger.error(f"Error calculating linguistic score: {str(e)}")
            linguistic_score = 0.5  # Default to neutral on error

        signals = {
            "perplexity": perplexity_score,
            "linguistic": linguistic_score,
        }

        # Classify content using both signals
        classification, confidence_score = classify_content(perplexity_score, linguistic_score)

        # Generate transparency label
        label_dict = generate_label(classification, confidence_score)
        transparency_label = label_dict

        # Generate submission ID and timestamp
        submission_id = str(uuid.uuid4())
        timestamp = datetime.utcnow().isoformat() + "Z"

        # Log to audit trail
        try:
            log_submission(
                content_id=submission_id,
                creator_id=creator_id,
                attribution=classification,
                confidence=round(confidence_score, 3),
                llm_score=round(perplexity_score, 3),
                linguistic_score=round(linguistic_score, 3),
                status="classified"
            )
        except Exception as e:
            logger.error(f"Error logging submission: {str(e)}")

        # Build response
        response = {
            "submission_id": submission_id,
            "classification": classification,
            "confidence_score": round(confidence_score, 3),
            "signals": {
                "perplexity": round(perplexity_score, 3),
                "linguistic": round(linguistic_score, 3),
            },
            "transparency_label": transparency_label,
            "timestamp": timestamp,
        }

        logger.info(
            f"Submission {submission_id} classified as {classification} "
            f"(confidence: {confidence_score:.3f})"
        )

        return jsonify(response), 200

    except Exception as e:
        logger.error(f"Unexpected error in /api/content/submit: {str(e)}")
        return jsonify({"error": "Internal server error."}), 500


@app.route("/health", methods=["GET"])
def health_check():
    """Health check endpoint."""
    return jsonify({"status": "healthy"}), 200


@app.route("/api/log", methods=["GET"])
def get_audit_log():
    """
    Retrieve audit log entries.

    Query parameters:
    - limit: Maximum number of entries to return (default: 10, max: 100)
    - offset: Number of entries to skip from the end (default: 0)

    Returns:
    {
        "entries": [
            {
                "content_id": "...",
                "creator_id": "...",
                "timestamp": "...",
                "attribution": "...",
                "confidence": 0.85,
                "llm_score": 0.75,
                "status": "..."
            },
            ...
        ],
        "count": 10
    }
    """
    try:
        limit = request.args.get("limit", 10, type=int)
        offset = request.args.get("offset", 0, type=int)

        # Clamp limit to reasonable values
        limit = max(1, min(100, limit))
        offset = max(0, offset)

        entries = get_log(limit=limit, offset=offset)

        return jsonify({
            "entries": entries,
            "count": len(entries)
        }), 200

    except Exception as e:
        logger.error(f"Error retrieving audit log: {str(e)}")
        return jsonify({"error": "Error retrieving audit log."}), 500


@app.route("/api/log/text", methods=["GET"])
def get_audit_log_text():
    """
    Retrieve audit log entries as formatted text.

    Query parameters:
    - limit: Maximum number of entries to return (default: 10, max: 100)

    Returns:
    Plain text formatted log entries.
    """
    try:
        limit = request.args.get("limit", 10, type=int)
        limit = max(1, min(100, limit))

        entries = get_log(limit=limit, offset=0)

        # Format as text
        text_output = "=== Provenance Guard Audit Log ===\n\n"
        for entry in entries:
            text_output += f"[{entry.get('content_id', 'N/A')[:8]}...] {entry.get('timestamp', 'N/A')}\n"
            text_output += f"  Creator: {entry.get('creator_id', 'N/A')}\n"
            text_output += f"  Attribution: {entry.get('attribution', 'N/A').upper()} ({entry.get('confidence', 0):.1%} confidence)\n"
            text_output += f"  Signal 1 (Perplexity): {entry.get('llm_score', 'N/A')}\n"
            text_output += f"  Status: {entry.get('status', 'N/A')}\n"
            text_output += "\n"

        return text_output, 200, {"Content-Type": "text/plain"}

    except Exception as e:
        logger.error(f"Error generating audit log text: {str(e)}")
        return "Error retrieving audit log.", 500, {"Content-Type": "text/plain"}


# ============================================================================
# Error Handlers
# ============================================================================

@app.errorhandler(429)
def ratelimit_handler(e):
    """Handle rate limit exceeded."""
    return jsonify({"error": "Rate limit exceeded. Maximum 100 requests per hour."}), 429


@app.errorhandler(405)
def method_not_allowed(e):
    """Handle method not allowed."""
    return jsonify({"error": "Method not allowed."}), 405


@app.errorhandler(404)
def not_found(e):
    """Handle route not found."""
    return jsonify({"error": "Endpoint not found."}), 404


# ============================================================================
# Entry Point
# ============================================================================

if __name__ == "__main__":
    logger.info("Starting Provenance Guard API...")
    app.run(debug=True, host="0.0.0.0", port=8000)
