"""
Label generation for Provenance Guard transparency labels and appeals processing.

This module provides:
1. generate_label() - Create transparency labels based on classification and confidence
2. generate_appeal_endpoint() - Flask endpoint handler for /api/appeals/submit
"""

import uuid
import logging
from datetime import datetime
from typing import Dict, Any, Tuple
from urllib.parse import urlparse

from flask import request, jsonify
from src.audit_log import get_submission_by_id, log_appeal

# Configure logging
logger = logging.getLogger(__name__)


# ============================================================================
# Label Generation
# ============================================================================

def generate_label(classification: str, confidence: float) -> Dict[str, str]:
    """
    Generate a transparency label based on classification and confidence score.

    Takes a classification result ("human", "ai", or "uncertain") and a confidence
    score (0-1), and returns a dictionary with the appropriate transparency label
    variant including title, description, and confidence level.

    Args:
        classification: One of "human", "ai", or "uncertain"
        confidence: Confidence score between 0 and 1

    Returns:
        Dictionary with keys:
        - "title": Short title (e.g., "✓ Likely written by a human")
        - "description": Full description text matching planning.md exactly
        - "confidence_level": One of "high", "medium", or "low"

    Examples:
        >>> label = generate_label("human", 0.75)
        >>> label["title"]
        '✓ Likely written by a human'
        >>> label["confidence_level"]
        'high'

        >>> label = generate_label("ai", 0.85)
        >>> label["title"]
        '⚠ Likely generated by AI'

        >>> label = generate_label("uncertain", 0.55)
        >>> label["title"]
        '? We\'re unsure about the authorship'
        >>> label["confidence_level"]
        'low'

    Logic:
        - IF classification == "human" AND confidence > 0.6:
          Return the "High-Confidence Human" variant with confidence_level="high"
        - IF classification == "ai" AND confidence > 0.6:
          Return the "High-Confidence AI" variant with confidence_level="high"
        - ELSE (classification == "uncertain" OR confidence <= 0.6):
          Return the "Uncertain" variant with confidence_level="low" or "medium"
    """
    # Determine confidence level
    if confidence > 0.7:
        confidence_level = "high"
    elif confidence > 0.5:
        confidence_level = "medium"
    else:
        confidence_level = "low"

    # High-Confidence Human
    if classification == "human" and confidence > 0.6:
        return {
            "title": "✓ Likely written by a human",
            "description": (
                "We're highly confident this content was written by a person.\n\n"
                "How we detected this:\n"
                "The writing shows natural variation in sentence structure and vocabulary "
                "choices that are typical of human authorship. The text uses diverse "
                "sentence lengths and includes natural discourse patterns."
            ),
            "confidence_level": "high",
        }

    # High-Confidence AI
    elif classification == "ai" and confidence > 0.6:
        return {
            "title": "⚠ Likely generated by AI",
            "description": (
                "We're highly confident this content was generated by an AI system, "
                "not written by a human.\n\n"
                "How we detected this:\n"
                "The text shows patterns of predictability and structural consistency "
                "that are typical of AI-generated content. Sentences have uniform length "
                "and structure, with formal discourse markers appearing systematically."
            ),
            "confidence_level": "high",
        }

    # Uncertain (fallback for classification=="uncertain" OR confidence <= 0.6)
    else:
        return {
            "title": "? We're unsure about the authorship",
            "description": (
                "Our analysis suggests this content has characteristics of both human "
                "and AI writing.\n\n"
                "This might mean:\n"
                "• The content is a blend of human and AI (e.g., AI draft revised by a human)\n"
                "• The writing style is unusual for our detection system\n"
                "• The author writes in a very formal or mechanical way\n"
                "• The text is too short for reliable analysis\n\n"
                "If you're the creator and this is your original work, you can appeal "
                "this classification."
            ),
            "confidence_level": confidence_level,
        }


# ============================================================================
# Appeal Validation
# ============================================================================

def validate_appeal_input(data: Dict[str, Any]) -> Tuple[bool, str]:
    """
    Validate the appeal request payload.

    Args:
        data: The JSON payload from the request.

    Returns:
        A tuple (is_valid, error_message). If is_valid is True, error_message is empty.
    """
    if not isinstance(data, dict):
        return False, "Request body must be a JSON object."

    # Check required fields
    required_fields = ["content_id", "creator_id", "reasoning"]
    for field in required_fields:
        if field not in data:
            return False, f"Missing required field: '{field}'."

    content_id = data.get("content_id")
    creator_id = data.get("creator_id")
    reasoning = data.get("reasoning")
    evidence = data.get("evidence")

    # Validate content_id
    if not isinstance(content_id, str):
        return False, "Field 'content_id' must be a string."

    if len(content_id.strip()) == 0:
        return False, "Field 'content_id' cannot be empty."

    # Validate creator_id
    if not isinstance(creator_id, str):
        return False, "Field 'creator_id' must be a string."

    if len(creator_id.strip()) == 0:
        return False, "Field 'creator_id' cannot be empty."

    # Validate reasoning (50-1000 characters)
    if not isinstance(reasoning, str):
        return False, "Field 'reasoning' must be a string."

    reasoning_length = len(reasoning.strip())
    if reasoning_length < 50:
        return False, "Field 'reasoning' must be at least 50 characters long."

    if reasoning_length > 1000:
        return False, "Field 'reasoning' must not exceed 1000 characters."

    # Validate evidence (optional, but if present should be valid URL)
    if evidence is not None:
        if not isinstance(evidence, str):
            return False, "Field 'evidence' must be a string."

        evidence_str = evidence.strip()
        if len(evidence_str) > 0:
            # Basic URL validation
            try:
                result = urlparse(evidence_str)
                if not all([result.scheme, result.netloc]):
                    return False, "Field 'evidence' must be a valid URL."
            except Exception:
                return False, "Field 'evidence' must be a valid URL."

    return True, ""


def is_valid_url(url: str) -> bool:
    """
    Check if a URL is valid.

    Args:
        url: URL string to validate.

    Returns:
        True if valid, False otherwise.
    """
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except Exception:
        return False


# ============================================================================
# Appeals Endpoint
# ============================================================================

def generate_appeal_endpoint(app):
    """
    Register the POST /api/appeals/submit endpoint with the Flask app.

    This function should be called after creating the Flask app to register
    the appeals endpoint.

    Args:
        app: The Flask application instance
    """

    @app.route("/api/appeals/submit", methods=["POST"])
    def submit_appeal():
        """
        Submit an appeal for a classification decision.

        POST /api/appeals/submit
        {
            "content_id": "submission-id",
            "creator_id": "user-id",
            "reasoning": "50-1000 characters explaining disagreement",
            "evidence": "optional-url"
        }

        Returns (200 OK):
        {
            "appeal_id": "unique-id",
            "content_id": "original-submission-id",
            "status": "under_review",
            "submitted_at": "ISO-8601-timestamp",
            "message": "Your appeal has been received and is under review."
        }

        Error responses:
        - 400: Invalid input (missing fields, reasoning length, invalid evidence URL)
        - 404: content_id not found in audit log
        - 409: Appeal already exists for this content_id
        """
        try:
            # Parse JSON
            data = request.get_json()
            if data is None:
                return jsonify({"error": "Request body must be valid JSON."}), 400

            # Validate input
            is_valid, error_msg = validate_appeal_input(data)
            if not is_valid:
                logger.warning(f"Invalid appeal input: {error_msg}")
                return jsonify({"error": error_msg}), 400

            content_id = data.get("content_id").strip()
            creator_id = data.get("creator_id").strip()
            reasoning = data.get("reasoning").strip()
            evidence = data.get("evidence")
            if evidence:
                evidence = evidence.strip()

            # Check if content_id exists in audit log
            submission = get_submission_by_id(content_id)
            if submission is None:
                logger.warning(f"Appeal submission failed: content_id '{content_id}' not found")
                return jsonify({"error": f"Submission with content_id '{content_id}' not found."}), 404

            # Check if appeal already exists for this content_id
            existing_appeals = submission.get("appeals", [])
            if len(existing_appeals) > 0:
                logger.warning(f"Appeal already exists for content_id '{content_id}'")
                return jsonify({
                    "error": "An appeal has already been submitted for this submission. "
                             "Multiple appeals per submission are not currently supported."
                }), 409

            # Generate unique appeal ID
            appeal_id = str(uuid.uuid4())
            timestamp = datetime.utcnow().isoformat() + "Z"

            # Log the appeal (this updates the audit log)
            try:
                log_appeal(
                    appeal_id=appeal_id,
                    content_id=content_id,
                    creator_id=creator_id,
                    reasoning=reasoning,
                    evidence=evidence if evidence else None,
                )
            except Exception as e:
                logger.error(f"Error logging appeal: {str(e)}")
                return jsonify({"error": "Internal server error while processing appeal."}), 500

            # Build response
            response = {
                "appeal_id": appeal_id,
                "content_id": content_id,
                "status": "under_review",
                "submitted_at": timestamp,
                "message": "Your appeal has been received and is under review.",
            }

            logger.info(
                f"Appeal {appeal_id} submitted for content {content_id} "
                f"by creator {creator_id}"
            )

            return jsonify(response), 200

        except Exception as e:
            logger.error(f"Unexpected error in /api/appeals/submit: {str(e)}")
            return jsonify({"error": "Internal server error."}), 500

    return app
