"""
Utility functions for the Provenance Guard system.
"""

import uuid
from typing import Tuple


def generate_content_id() -> str:
    """Generate a unique content ID."""
    return str(uuid.uuid4())


def map_score_to_attribution(final_score: float) -> str:
    """
    Map a final confidence score to an attribution label.

    Args:
        final_score: Combined score from signals (0-1)

    Returns:
        Attribution string: "likely_human", "likely_ai", or "uncertain"
    """
    if final_score > 0.75:
        return "likely_human"
    elif final_score < 0.25:
        return "likely_ai"
    else:
        return "uncertain"


def calculate_confidence(final_score: float) -> float:
    """
    Calculate confidence as distance from decision boundary.

    confidence = 2 × |finalScore - 0.5|

    Args:
        final_score: Combined signal score (0-1)

    Returns:
        Confidence score (0-1)
    """
    return 2 * abs(final_score - 0.5)


def get_label_for_attribution(
    attribution: str, confidence: float
) -> Tuple[str, str, str]:
    """
    Get the transparency label for an attribution result.

    Args:
        attribution: Classification result ("likely_human", "likely_ai", "uncertain")
        confidence: Confidence score (0-1)

    Returns:
        Tuple of (title, description, icon)
    """
    if attribution == "likely_human":
        return (
            "✓ Likely written by a human",
            "We're highly confident this content was written by a person.\n\n"
            "How we detected this:\n"
            "The writing shows natural variation in sentence structure and vocabulary "
            "choices that are typical of human authorship. The text uses diverse "
            "sentence lengths and includes natural discourse patterns.",
            "✓",
        )
    elif attribution == "likely_ai":
        return (
            "⚠ Likely generated by AI",
            "We're highly confident this content was generated by an AI system, "
            "not written by a human.\n\n"
            "How we detected this:\n"
            "The text shows patterns of predictability and structural consistency "
            "that are typical of AI-generated content. Sentences have uniform length "
            "and structure, with formal discourse markers appearing systematically.",
            "⚠",
        )
    else:  # uncertain
        return (
            "? We're unsure about the authorship",
            "Our analysis suggests this content has characteristics of both human "
            "and AI writing.\n\n"
            "This might mean:\n"
            "• The content is a blend of human and AI (e.g., AI draft revised by a human)\n"
            "• The writing style is unusual for our detection system\n"
            "• The author writes in a very formal or mechanical way\n"
            "• The text is too short for reliable analysis\n\n"
            "If you're the creator and this is your original work, you can appeal "
            "this classification.",
            "?",
        )
